// * Copyright (c) 2015-2021 Cirrus Link Solutions and others
// *
// * This program and the accompanying materials are made available under the
// * terms of the Eclipse Public License 2.0 which is available at
// * http://www.eclipse.org/legal/epl-2.0.
// *
// * SPDX-License-Identifier: EPL-2.0
// *
// * Contributors:
// *   Cirrus Link Solutions - initial implementation

//
// To compile:
// cd client_libraries/java
// protoc --proto_path=../../ --java_out=src/main/java ../../sparkplug_b.proto
//

syntax = "proto2";

package org.eclipse.tahu.protobuf;

option java_package         = "org.eclipse.tahu.protobuf";
option java_outer_classname = "SparkplugBProto";

enum DataType {
    // Indexes of Data Types

    // Unknown placeholder for future expansion.
    Unknown         = 0;

    // Basic Types
    Int8            = 1;
    Int16           = 2;
    Int32           = 3;
    Int64           = 4;
    UInt8           = 5;
    UInt16          = 6;
    UInt32          = 7;
    UInt64          = 8;
    Float           = 9;
    Double          = 10;
    Boolean         = 11;
    String          = 12;
    DateTime        = 13;
    Text            = 14;

    // Additional Metric Types
    UUID            = 15;
    DataSet         = 16;
    Bytes           = 17;
    File            = 18;
    Template        = 19;

    // Additional PropertyValue Types
    PropertySet     = 20;
    PropertySetList = 21;

    // Array Types
    Int8Array = 22;
    Int16Array = 23;
    Int32Array = 24;
    Int64Array = 25;
    UInt8Array = 26;
    UInt16Array = 27;
    UInt32Array = 28;
    UInt64Array = 29;
    FloatArray = 30;
    DoubleArray = 31;
    BooleanArray = 32;
    StringArray = 33;
    DateTimeArray = 34;
}

message Payload {

    message TypedValue {
        optional DataType datatype = 1;
        optional bool     is_null  = 2;

        oneof value {
            int32    int32_value                    = 3;
            int64    int64_value                    = 4;
            uint32   uint32_value                   = 5;
            uint64   uint64_value                   = 6;
            float    float_value                    = 7;
            double   double_value                   = 8;
            bool     boolean_value                  = 9;
            string   string_value                   = 10;
            bytes    bytes_value                    = 11;
            DataSet  dataset_value                  = 12;
            Template template_value                 = 13;
            PropertySet     propertyset_value       = 14;
            PropertySetList propertysets_value      = 15;
            TypedValueExtension extension_value     = 16;
        }

        message TypedValueExtension {
            extensions  1 to max;
        }

        extensions 17 to max;
    }

    message Template {

        message Parameter {
            optional string name            = 1;
            optional TypedValue typed_value = 2;
            extensions                      3 to max;
        }

        optional string version         = 1;          // The version of the Template to prevent mismatches
        repeated Metric metrics         = 2;          // Each metric includes a name, datatype, and optionally a value
        repeated Parameter parameters   = 3;
        optional string template_ref    = 4;          // MUST be a reference to a template definition if this is an instance (i.e. the name of the template definition) - MUST be omitted for template definitions
        optional bool is_definition     = 5;
        extensions                      6 to max;
    }

    message DataSet {

        message Column {
            optional string name     = 1;
            optional DataType datatype = 2;

            // Only one type of repeated value shall be used per Column
            repeated uint32 int_values       = 3 [packed=true];
            repeated uint64 long_values      = 4 [packed=true];
            repeated float  float_values     = 5 [packed=true];
            repeated double double_values    = 6 [packed=true];
            repeated bool   boolean_values   = 7 [packed=true];
            repeated string string_values    = 8 [packed=false];

            extensions                       9 to max;
        }

        repeated Column columns              = 1;
        extensions                           2 to max;
    }

    message PropertySet {
        repeated string        keys     = 1;         // Names of the properties
        repeated TypedValue    values   = 2;         // The Property Values
        extensions                      3 to max;
    }

    message PropertySetList {
        repeated PropertySet propertyset = 1;
        extensions                       2 to max;
    }

    message MetaData {
        // Bytes specific metadata
        optional bool   is_multi_part   = 1;

        // General metadata
        optional string content_type    = 2;        // Content/Media type
        optional uint64 size            = 3;        // File size, String size, Multi-part size, etc
        optional uint64 seq             = 4;        // Sequence number for multi-part messages

        // File metadata
        optional string file_name       = 5;        // File name
        optional string file_type       = 6;        // File type (i.e. xml, json, txt, cpp, etc)
        optional string md5             = 7;        // md5 of data

        // Others
        optional string description     = 8;        // Could be anything such as json or xml of custom properties
        optional string engUnit         = 9;        // Engineering units

        // Future expansion
        extensions                      10 to max;
    }

    message Metric {

        optional string   name          = 1;        // Metric name - Required in BIRTH messages, optional in DATA messages if using aliases
        optional uint64   alias         = 2;        // Metric alias - tied to name on BIRTH and included in all later DATA messages
        optional uint64   timestamp     = 3;        // Timestamp associated with data acquisition time - if omitted, the overall payload timestamp is assumed as the data acquisition time
        optional DataType datatype      = 4;        // DataType of the metric/tag value
        optional string   source        = 5;        // Source for CMD messages if unique to the Metric (typically for forwarded writes in CMD messages)
        optional bool     is_historical = 6;        // If this is historical data and should not update real time tag
        optional bool     is_transient  = 7;        // Tells consuming clients such as MQTT Engine to not store this as a tag
        optional bool     is_null       = 8;        // If this is null - explicitly say so rather than using -1, false, etc for some datatypes.
        optional MetaData metadata      = 9;        // Metadata for the Metric
        optional PropertySet properties = 10;       // Properties of the Metric
        optional TypedValue value       = 11;
        extensions 12 to max;
    }

    optional uint64   timestamp     = 1;        // Timestamp at message sending time
    repeated Metric   metrics       = 2;        // Repeated forever - no limit in Google Protobufs
    optional uint64   seq           = 3;        // Message sequence number
    optional uint64   bd_seq        = 4;        // The Birth/Death sequence number for BIRTH and DEATH payloads
    optional string   source        = 5;        // Source for CMD and REBIRTH messages - the Host Application ID that sent the message
    optional string   uuid          = 6;        // UUID to track message type in terms of schema definitions
    optional bytes    body          = 7;        // To optionally bypass the whole definition above
    extensions                      8 to max;   // For third party extensions
}
